networks:
  custom:
    driver: bridge

services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: react-video-uploader-node
    volumes:
      - ./:/home/node/app
      - ./docker/node/.bash_history:/home/node/.bash_history
      - ./node-cache:/home/node/.cache
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - custom
    #dns:
      #- 8.8.8.8
      #- 8.8.8.4
    ports:
      - '3003:3000'
      #- '8080:8080'
    restart: unless-stopped
    tty: true
    # For playwright - kills zombie 🧟 processes
    init: true
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      DISPLAY: ${DISPLAY:-:0}
      IS_DOCKER: 1
      TZ: ${TZ:-Australia/Sydney}

#  git_hook_installer:
#    image: sharpdressedcodes/git-hooks-installer:1.0.0-stretch-slim
#    #    build:
#    #      context: docker/git_hooks_installer
#    #      dockerfile: Dockerfile
#    #      args:
#    #        - USER_ID=${USER_ID:-0}
#    #        - USER_NAME=${USER_NAME:-node}
#    #        - GROUP_ID=${GROUP_ID:-0}
#    #        - GROUP_NAME=${GROUP_NAME:-node}
#    container_name: git_hook_installer
#    volumes:
#      - ./.git:/tmp/.git
#      - ./hooks:/tmp/hooks
#    networks:
#      - custom
