version: '3.4'

networks:
  custom:
    driver: bridge

services:
  node:
    #image: sharpdressedcodes/node:16.15.0-bullseye-slim
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./:/home/node/app
    networks:
      - custom
    ports:
      - '3000:3000'
    restart: unless-stopped
    tty: true
    working_dir: /home/node/app
    environment:
      IS_DOCKER: 1
      TZ: ${TZ:-Australia/Sydney}
