version: '3.4'

networks:
  custom:
    driver: bridge

services:
  node:
    #image: sharpdressedcodes/node:16.15.0-bullseye-slim
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./:/home/node/app
    networks:
      - custom
    ports:
      - '3000:3000'
      - '8080:8080'
    restart: unless-stopped
    tty: true
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      IS_DOCKER: 1
      TZ: ${TZ:-Australia/Sydney}

  git_hook_installer:
    image: sharpdressedcodes/git-hooks-installer:1.0.0-stretch-slim
    #    build:
    #      context: docker/git_hooks_installer
    #      dockerfile: Dockerfile
    #      args:
    #        - USER_ID=${USER_ID:-0}
    #        - USER_NAME=${USER_NAME:-node}
    #        - GROUP_ID=${GROUP_ID:-0}
    #        - GROUP_NAME=${GROUP_NAME:-node}
    container_name: git_hook_installer
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
    networks:
      - custom
