version: '3.4'

networks:
  custom:
    driver: bridge

services:
  node:
    #image: sharpdressedcodes/node:18.16.0-bullseye-slim
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: node
    volumes:
      - ./:/home/node/app
    networks:
      - custom
    ports:
      - '3000:3000'
    restart: unless-stopped
    tty: true
    working_dir: /home/node/app
    environment:
      IS_DOCKER: 1
      TZ: ${TZ:-Australia/Sydney}
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
