name: CI_merge_to_master

on:
  pull_request:
    types: [closed]
    branches:
      - master

  #push:
  #  branches:
  #    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    #if: github.event.action == 'closed' && github.event.pull_request.merged == true
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04

    # This workflow contains a single job called "build"
    #build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run deployment
        env:
          IS_DOCKER: 1
          TZ: Australia/Sydney
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "🚀 Successfully merged 🚀"
