name: CI_pull_request

on:
  pull_request:
    branches:
      - fix/*
      - feature/*

  push:
    branches:
      - fix/*
      - feature/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run linting, unit tests, auditing and build process
        env:
          IS_DOCKER: 1
          TZ: Australia/Sydney
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          export USER_ID=`id -u`
          export GROUP_ID=`id -g`
          export CYPRESS_CACHE_FOLDER=/home/node/app/.cypress-cache
          echo "$(grep -v '"cypress":' package.json)" >package.json
          cat package.json
          docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
          USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml down
          USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml up -d --build
          docker ps -a
          \
          echo "USER_ID=${USER_ID} GROUP_ID=${GROUP_ID}"
          \
          echo "Installing dependencies..."
          CYPRESS_CACHE_FOLDER=/home/node/app/.cypress-cache USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml exec -T --user root node npm i
          \
          echo "Running linting..."
          USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml exec -T --user node node npm run lint
          \
          echo "Running unit tests..."
          USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml exec -T --user node node npm run test:ci
          \
          echo "Running build process..."
          USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml exec -T --user node node npm run build
          \
          echo "Running audit..."
          USER_ID=`id -u` GROUP_ID=`id -g` && docker-compose -f docker-compose.ci.yml exec -T --user node node npm run audit:ci
          \
          echo "🚀 Passed all checks successfully 💪"
