name: CI_pull_request

on:
  pull_request:
    branches:
      - fix/*
      - feature/*

  push:
    branches:
      - fix/*
      - feature/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run linting, unit tests, build process, e2e tests and audit
        env:
          IS_DOCKER: 1
          TZ: Australia/Sydney
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        # Remove cypress since we will run that in its own container anyway.
        # NOTE: using `echo "" &&` below otherwise the commands fail. Need to work out why this happens.
        run: |
          export USER_ID=`id -u`
          export GROUP_ID=`id -g`
          docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
          docker-compose -f docker-compose.ci.yml down
          docker-compose -f docker-compose.ci.yml up -d --build
          docker ps -a
          \
          echo "Installing dependencies..."
          echo "$(grep -v '"cypress":' package.json)" >package.json
          docker-compose -f docker-compose.ci.yml exec -T node echo "" && npm i --legacy-peer-deps --foreground-scripts
          \
          echo "Running linting..."
          docker-compose -f docker-compose.ci.yml exec -T node npm run lint
          \
          echo "Running unit tests..."
          docker-compose -f docker-compose.ci.yml exec -T node npm run test:ci
          \
          echo "Running build process..."
          docker-compose -f docker-compose.ci.yml exec -T node npm run build:ci
          \
          echo "Running audit..."
          docker-compose -f docker-compose.ci.yml exec -T node npm run audit:ci
          \
          echo "🚀 Passed all checks successfully 💪"
